# -------------------------------------------------------------------------------------
# Author Configuration
# -------------------------------------------------------------------------------------

name = "Karl"
email = "karl@malware.to"
link = "https://github.com/StasonJatham"
avatar = "/karl_square_yellow_back.jpeg"
about_me = "The name is Karl. I have been doing IT-Security for the best part of the last 10 yearsğŸ‘´. My main focus these days is OSINTğŸ•µï¸â€â™‚ï¸, researchğŸ§ª and tool developmentğŸ‘¨â€ğŸ’». I also enjoy gamingğŸ®, boulderingğŸª¨, hikingğŸ¥¾ and pizzağŸ•."
